// <auto-generated />
using System;
using CarRental.Infrastructure.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarRental.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(CarRentalDbContext))]
    [Migration("20251223142141_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarRental.Domain.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<int>("GenerationId")
                        .HasColumnType("integer")
                        .HasColumnName("generation_id");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license_plate");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId");

                    b.ToTable("cars", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Белый",
                            GenerationId = 1,
                            LicensePlate = "I101DH"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Черный",
                            GenerationId = 2,
                            LicensePlate = "O122OP"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Серый",
                            GenerationId = 3,
                            LicensePlate = "C323OB"
                        },
                        new
                        {
                            Id = 4,
                            Color = "Белый",
                            GenerationId = 4,
                            LicensePlate = "M234PP"
                        },
                        new
                        {
                            Id = 5,
                            Color = "Черный",
                            GenerationId = 5,
                            LicensePlate = "A754BA"
                        },
                        new
                        {
                            Id = 6,
                            Color = "Серый",
                            GenerationId = 6,
                            LicensePlate = "Y349KY"
                        },
                        new
                        {
                            Id = 7,
                            Color = "Белый",
                            GenerationId = 7,
                            LicensePlate = "Т009ТР"
                        },
                        new
                        {
                            Id = 8,
                            Color = "Черный",
                            GenerationId = 8,
                            LicensePlate = "Р108ВР"
                        },
                        new
                        {
                            Id = 9,
                            Color = "Серый",
                            GenerationId = 9,
                            LicensePlate = "А166СС"
                        },
                        new
                        {
                            Id = 10,
                            Color = "Белый",
                            GenerationId = 10,
                            LicensePlate = "M110LC"
                        },
                        new
                        {
                            Id = 11,
                            Color = "Черный",
                            GenerationId = 11,
                            LicensePlate = "E111EP"
                        },
                        new
                        {
                            Id = 12,
                            Color = "Серый",
                            GenerationId = 12,
                            LicensePlate = "Е751ОВ"
                        },
                        new
                        {
                            Id = 13,
                            Color = "Белый",
                            GenerationId = 13,
                            LicensePlate = "К361ЛО"
                        },
                        new
                        {
                            Id = 14,
                            Color = "Черный",
                            GenerationId = 14,
                            LicensePlate = "А100МР"
                        },
                        new
                        {
                            Id = 15,
                            Color = "Серый",
                            GenerationId = 15,
                            LicensePlate = "А185ЛР"
                        });
                });

            modelBuilder.Entity("CarRental.Domain.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license_number");

                    b.HasKey("Id");

                    b.ToTable("clients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1990, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ivanov Ivan Ivanovich",
                            LicenseNumber = "133416"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1985, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Petrov Alexey Sergeevich",
                            LicenseNumber = "214567"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1992, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Sidorova Maria Pavlovna",
                            LicenseNumber = "341178"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1988, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Kuznetsov Dmitry Alekseevich",
                            LicenseNumber = "436489"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1995, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Smirnova Ekaterina Nikolaevna",
                            LicenseNumber = "577890"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1983, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Popov Sergey Viktorovich",
                            LicenseNumber = "688901"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1991, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Vasilyeva Olga Mikhailovna",
                            LicenseNumber = "789092"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1987, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Morozova Natalia Andreevna",
                            LicenseNumber = "850173"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1993, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Fyodorov Andrey Petrovich",
                            LicenseNumber = "901534"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1989, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Kovalev Pavel Yurievich",
                            LicenseNumber = "012045"
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(1994, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Novikova Elena Anatolyevna",
                            LicenseNumber = "115033"
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(1986, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Zaitsev Mikhail Fedorovich",
                            LicenseNumber = "223544"
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateTime(1990, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Sokolova Svetlana Nikolaevna",
                            LicenseNumber = "332455"
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateTime(1984, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Lebedev Konstantin Vyacheslavovich",
                            LicenseNumber = "447766"
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateTime(1988, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Gusev Alexey Konstantinovich",
                            LicenseNumber = "580677"
                        });
                });

            modelBuilder.Entity("CarRental.Domain.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_type");

                    b.Property<string>("CarClass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("car_class");

                    b.Property<string>("DriveType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("drive_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Seats")
                        .HasColumnType("integer")
                        .HasColumnName("seats");

                    b.HasKey("Id");

                    b.ToTable("models", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BodyType = "Седан",
                            CarClass = "Эконом",
                            DriveType = "Передний",
                            Name = "Toyota Corolla",
                            Seats = 5
                        },
                        new
                        {
                            Id = 2,
                            BodyType = "Кроссовер",
                            CarClass = "Премиум",
                            DriveType = "Полный",
                            Name = "BMW X5",
                            Seats = 5
                        },
                        new
                        {
                            Id = 3,
                            BodyType = "Седан",
                            CarClass = "Эконом",
                            DriveType = "Передний",
                            Name = "Kia Rio",
                            Seats = 5
                        },
                        new
                        {
                            Id = 4,
                            BodyType = "Седан",
                            CarClass = "Бизнес",
                            DriveType = "Передний",
                            Name = "Audi A4",
                            Seats = 5
                        },
                        new
                        {
                            Id = 5,
                            BodyType = "Седан",
                            CarClass = "Эконом",
                            DriveType = "Передний",
                            Name = "Lada Vesta",
                            Seats = 5
                        },
                        new
                        {
                            Id = 6,
                            BodyType = "Седан",
                            CarClass = "Премиум",
                            DriveType = "Полный",
                            Name = "Tesla Model 3",
                            Seats = 5
                        },
                        new
                        {
                            Id = 7,
                            BodyType = "Седан",
                            CarClass = "Эконом",
                            DriveType = "Передний",
                            Name = "Volkswagen Polo",
                            Seats = 5
                        },
                        new
                        {
                            Id = 8,
                            BodyType = "Кроссовер",
                            CarClass = "Средний",
                            DriveType = "Полный",
                            Name = "Hyundai Tucson",
                            Seats = 5
                        },
                        new
                        {
                            Id = 9,
                            BodyType = "Седан",
                            CarClass = "Бизнес",
                            DriveType = "Задний",
                            Name = "Mercedes C-Class",
                            Seats = 5
                        },
                        new
                        {
                            Id = 10,
                            BodyType = "Кроссовер",
                            CarClass = "Средний",
                            DriveType = "Полный",
                            Name = "Renault Duster",
                            Seats = 5
                        },
                        new
                        {
                            Id = 11,
                            BodyType = "Седан",
                            CarClass = "Бизнес",
                            DriveType = "Передний",
                            Name = "Mazda 6",
                            Seats = 5
                        },
                        new
                        {
                            Id = 12,
                            BodyType = "Кроссовер",
                            CarClass = "Средний",
                            DriveType = "Полный",
                            Name = "Nissan Qashqai",
                            Seats = 5
                        },
                        new
                        {
                            Id = 13,
                            BodyType = "Седан",
                            CarClass = "Средний",
                            DriveType = "Передний",
                            Name = "Skoda Octavia",
                            Seats = 5
                        },
                        new
                        {
                            Id = 14,
                            BodyType = "Внедорожник",
                            CarClass = "Премиум",
                            DriveType = "Полный",
                            Name = "Chevrolet Tahoe",
                            Seats = 8
                        },
                        new
                        {
                            Id = 15,
                            BodyType = "Седан",
                            CarClass = "Эконом",
                            DriveType = "Передний",
                            Name = "Ford Focus",
                            Seats = 5
                        });
                });

            modelBuilder.Entity("CarRental.Domain.Models.ModelGeneration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("EngineVolume")
                        .HasColumnType("double precision")
                        .HasColumnName("engine_volume");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer")
                        .HasColumnName("model_id");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price_per_hour");

                    b.Property<string>("TransmissionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transmission_type");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("model_generations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EngineVolume = 1.6000000000000001,
                            ModelId = 1,
                            PricePerHour = 1000m,
                            TransmissionType = "Автомат",
                            Year = 2020
                        },
                        new
                        {
                            Id = 2,
                            EngineVolume = 2.0,
                            ModelId = 2,
                            PricePerHour = 2000m,
                            TransmissionType = "Автомат",
                            Year = 2021
                        },
                        new
                        {
                            Id = 3,
                            EngineVolume = 1.3999999999999999,
                            ModelId = 3,
                            PricePerHour = 2500m,
                            TransmissionType = "Механика",
                            Year = 2019
                        },
                        new
                        {
                            Id = 4,
                            EngineVolume = 2.0,
                            ModelId = 4,
                            PricePerHour = 1900m,
                            TransmissionType = "Автомат",
                            Year = 2020
                        },
                        new
                        {
                            Id = 5,
                            EngineVolume = 1.6000000000000001,
                            ModelId = 5,
                            PricePerHour = 1000m,
                            TransmissionType = "Механика",
                            Year = 2018
                        },
                        new
                        {
                            Id = 6,
                            EngineVolume = 1.2,
                            ModelId = 6,
                            PricePerHour = 8000m,
                            TransmissionType = "Автомат",
                            Year = 2022
                        },
                        new
                        {
                            Id = 7,
                            EngineVolume = 1.3999999999999999,
                            ModelId = 7,
                            PricePerHour = 1250m,
                            TransmissionType = "Механика",
                            Year = 2020
                        },
                        new
                        {
                            Id = 8,
                            EngineVolume = 2.0,
                            ModelId = 8,
                            PricePerHour = 2000m,
                            TransmissionType = "Автомат",
                            Year = 2021
                        },
                        new
                        {
                            Id = 9,
                            EngineVolume = 2.0,
                            ModelId = 9,
                            PricePerHour = 2500m,
                            TransmissionType = "Автомат",
                            Year = 2019
                        },
                        new
                        {
                            Id = 10,
                            EngineVolume = 1.6000000000000001,
                            ModelId = 10,
                            PricePerHour = 2300m,
                            TransmissionType = "Механика",
                            Year = 2020
                        },
                        new
                        {
                            Id = 11,
                            EngineVolume = 2.0,
                            ModelId = 11,
                            PricePerHour = 3000m,
                            TransmissionType = "Автомат",
                            Year = 2020
                        },
                        new
                        {
                            Id = 12,
                            EngineVolume = 1.6000000000000001,
                            ModelId = 12,
                            PricePerHour = 2500m,
                            TransmissionType = "Автомат",
                            Year = 2021
                        },
                        new
                        {
                            Id = 13,
                            EngineVolume = 1.8,
                            ModelId = 13,
                            PricePerHour = 2500m,
                            TransmissionType = "Механика",
                            Year = 2019
                        },
                        new
                        {
                            Id = 14,
                            EngineVolume = 5.2999999999999998,
                            ModelId = 14,
                            PricePerHour = 8000m,
                            TransmissionType = "Автомат",
                            Year = 2025
                        },
                        new
                        {
                            Id = 15,
                            EngineVolume = 1.6000000000000001,
                            ModelId = 15,
                            PricePerHour = 1250m,
                            TransmissionType = "Автомат",
                            Year = 2018
                        });
                });

            modelBuilder.Entity("CarRental.Domain.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer")
                        .HasColumnName("car_id");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<int>("DurationHours")
                        .HasColumnType("integer")
                        .HasColumnName("duration_hours");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("ClientId");

                    b.ToTable("rentals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            ClientId = 1,
                            DurationHours = 5,
                            StartTime = new DateTime(2025, 11, 10, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CarId = 3,
                            ClientId = 1,
                            DurationHours = 2,
                            StartTime = new DateTime(2025, 11, 12, 19, 2, 2, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CarId = 1,
                            ClientId = 1,
                            DurationHours = 5,
                            StartTime = new DateTime(2025, 11, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CarId = 6,
                            ClientId = 1,
                            DurationHours = 6,
                            StartTime = new DateTime(2025, 11, 18, 10, 5, 5, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CarId = 2,
                            ClientId = 2,
                            DurationHours = 30,
                            StartTime = new DateTime(2025, 11, 9, 10, 1, 1, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CarId = 11,
                            ClientId = 2,
                            DurationHours = 6,
                            StartTime = new DateTime(2025, 11, 17, 13, 10, 10, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CarId = 3,
                            ClientId = 3,
                            DurationHours = 4,
                            StartTime = new DateTime(2025, 11, 3, 11, 2, 2, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CarId = 10,
                            ClientId = 3,
                            DurationHours = 3,
                            StartTime = new DateTime(2025, 11, 20, 10, 9, 9, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CarId = 5,
                            ClientId = 4,
                            DurationHours = 6,
                            StartTime = new DateTime(2025, 11, 4, 12, 4, 4, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CarId = 14,
                            ClientId = 5,
                            DurationHours = 2,
                            StartTime = new DateTime(2025, 11, 5, 9, 13, 13, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CarId = 4,
                            ClientId = 5,
                            DurationHours = 5,
                            StartTime = new DateTime(2025, 11, 22, 11, 3, 3, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            CarId = 10,
                            ClientId = 6,
                            DurationHours = 5,
                            StartTime = new DateTime(2025, 11, 6, 12, 9, 9, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            CarId = 3,
                            ClientId = 6,
                            DurationHours = 6,
                            StartTime = new DateTime(2025, 11, 7, 11, 2, 2, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            CarId = 15,
                            ClientId = 6,
                            DurationHours = 4,
                            StartTime = new DateTime(2025, 11, 9, 14, 14, 14, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            CarId = 7,
                            ClientId = 6,
                            DurationHours = 3,
                            StartTime = new DateTime(2025, 11, 11, 10, 6, 6, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            CarId = 15,
                            ClientId = 6,
                            DurationHours = 7,
                            StartTime = new DateTime(2025, 11, 25, 9, 14, 14, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            CarId = 3,
                            ClientId = 7,
                            DurationHours = 3,
                            StartTime = new DateTime(2025, 11, 7, 9, 2, 2, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            CarId = 1,
                            ClientId = 8,
                            DurationHours = 4,
                            StartTime = new DateTime(2025, 11, 8, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            CarId = 12,
                            ClientId = 8,
                            DurationHours = 2,
                            StartTime = new DateTime(2025, 11, 28, 15, 11, 11, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            CarId = 9,
                            ClientId = 9,
                            DurationHours = 6,
                            StartTime = new DateTime(2025, 11, 9, 11, 8, 8, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            CarId = 10,
                            ClientId = 10,
                            DurationHours = 2,
                            StartTime = new DateTime(2025, 11, 10, 12, 9, 9, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            CarId = 7,
                            ClientId = 10,
                            DurationHours = 4,
                            StartTime = new DateTime(2025, 11, 1, 8, 6, 6, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            CarId = 11,
                            ClientId = 11,
                            DurationHours = 5,
                            StartTime = new DateTime(2025, 11, 11, 9, 10, 10, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            CarId = 12,
                            ClientId = 12,
                            DurationHours = 3,
                            StartTime = new DateTime(2025, 11, 12, 14, 11, 11, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            CarId = 3,
                            ClientId = 13,
                            DurationHours = 4,
                            StartTime = new DateTime(2025, 11, 13, 9, 2, 2, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 26,
                            CarId = 4,
                            ClientId = 14,
                            DurationHours = 6,
                            StartTime = new DateTime(2025, 11, 14, 10, 3, 3, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 27,
                            CarId = 6,
                            ClientId = 15,
                            DurationHours = 4,
                            StartTime = new DateTime(2025, 11, 18, 11, 5, 5, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 28,
                            CarId = 5,
                            ClientId = 15,
                            DurationHours = 2,
                            StartTime = new DateTime(2025, 11, 15, 11, 4, 4, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CarRental.Domain.Models.Car", b =>
                {
                    b.HasOne("CarRental.Domain.Models.ModelGeneration", "Generation")
                        .WithMany()
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("CarRental.Domain.Models.ModelGeneration", b =>
                {
                    b.HasOne("CarRental.Domain.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("CarRental.Domain.Models.Rental", b =>
                {
                    b.HasOne("CarRental.Domain.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRental.Domain.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
